#!/bin/sh
### BEGIN INIT INFO
# Provides:          tempmon
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 5
# Default-Stop:
# Short-Description: Temperature Monitor
# Description: Monitors processor's temperature
#              and send an e-mail if it is too high
### END INIT INFO

RUN_DIR=/home/pi/temperature_monitor
LOG_FILE=temp_mon.log

case "$1" in
  start)

    if [ -e $RUN_DIR/$LOG_FILE ];
        then
            file_size=`du -k "$RUN_DIR/$LOG_FILE" | cut -f1`
        else
            file_fsize=0
    fi

    if [ $file_size -gt 100 ];
        then
            rm $RUN_DIR/$LOG_FILE
    fi

    sleep 60
    su pi -c $RUN_DIR/temp-mon.py

    ;;

  *)
    break
    ;;

esac


