#!/bin/sh
### BEGIN INIT INFO
# Provides:          tempmon
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 5
# Default-Stop:
# Short-Description: Temperature Monitor
# Description: Monitors processor's temperature
#              and send an e-mail if it is too high
### END INIT INFO

case "$1" in
  start)
    rm /home/pi/temperature_monitor/temp_mon.log
    su pi -c /home/pi/temperature_monitor/temp_mon.py
    ;;

  *)
    break
    ;;

esac


